### ISSUE TITLE
Python dependencies: add paramiko, and consider official pip package requirements file?

### ISSUE THREAD

**Issue by gunnarx** [svlad-90/paf#1]
I had to pip install **paramiko** and that could be added in README.

More generally, have you considered using a **requirements.txt** or **Pipfile** to officially define the dependencies?

**Comment by svlad-90** [comment]
Hi @gunnarx, 

First of all, thanks for reporting this issue!

As of now, README section contains information about the external python modules:

![image](https://user-images.githubusercontent.com/4373469/154091035-86ccf83f-6b17-43a1-93d8-cdcce4972523.png)
![image](https://user-images.githubusercontent.com/4373469/154090963-e00ba1f2-bf5c-44c7-8085-d92ad50da7de.png)

But you are right. It has no information about the paramiko.

=> I will extend README.
=> Also, I will read more about the Pipfile. It would be great to automate the resolution of dependencies.

**P.S. It'll take ~3 calendar days to react to this request.**

**Comment by svlad-90** [comment]
Hi @gunnarx, the issue was fixed.

I've added Pipfile and Pipfile.lock, which do cover all external dependencies:

![image](https://user-images.githubusercontent.com/4373469/154674049-4e4cd05d-cb8b-434d-b81d-781726a86f82.png)

Also, I've extended the README to cover the new way to resolve the dependencies:

![image](https://user-images.githubusercontent.com/4373469/154673963-72bf5568-a9bf-4afe-8152-a14844979b4b.png)

Verification of execution PAF inside the virtenv was successful:

![image](https://user-images.githubusercontent.com/4373469/154674271-9e4465d6-3dac-4fa3-815c-9a6a3229e918.png)
